# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PracticeSnapKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '13.0'

  pod 'SnapKit', '~> 5.6.0'
  # Pods for PracticeSnapKit

  target 'PracticeSnapKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PracticeSnapKitUITests' do
    # Pods for testing
  end

end
