# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'thenPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Then'
  pod 'Tabman', '~> 3.0'
  # Pods for thenPractice

end
